[versions]
activityCompose = "1.12.2"
androidGradlePlugin = "8.13.2"
appcompat = "1.7.1"
composeMultiplatform = "1.9.3"
coreKtx = "1.17.0"
dokka = "2.1.0"
kotlin = "2.3.0"
kotlinCollectionsImmutable = "0.4.0"
ktlint = "1.8.0"
lifecycleRuntimeKtx = "2.10.0"
paparazzi = "2.0.0-alpha02"
pigment = "0.6.0"
spotless = "8.1.0"
testParameterInjector = "1.20"
vanniktechMavenPublishPlugin = "0.33.0"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

androidx-lifecycle-runtimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

google-testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }

kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinCollectionsImmutable" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublishPlugin" }
